- name: Retail-edge VM cleanup_old_vms playbook
  hosts: edge # use ansible-playbook -l group to limit application to specific groups - has tab completion for -l !
  connection: ansible.builtin.local
  gather_facts: false
  strategy: host_pinned # free  #allows each cluster to start next task before all clusters have finished current task
  environment:
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}"
    SC_PASSWORD: "{{ scale_pass }}"

  tasks:
# cleanup old / no longer needed VMs
  - name: Clean up old vms  # example of removing any old template or vm
    scale_computing.hypercore.vm:
      vm_name: "{{ item }}"
      state: absent
    loop:
      - ubuntu20_0
      - oldvm
      - demo1
      - "demo1-{{ site_name }}"
      - demo2