---
- name: get cluster info using scale_computing.hypercore.api module
  hosts: all # use ansible-playbook -l group to limit application to specific groups
  connection: ansible.builtin.local
  gather_facts: False
  #strategy: host_pinned #free  #allows each cluster to start next task before all clusters have finished current task

  
  tasks:

  - name: check web access - api 
    uri:
      url: http://{{ansible_host}}/rest/v1/docs
      method: GET
      return_content: yes
      status_code: 200
      validate_certs: false
    failed_when: "'Scale API' not in data.content"
    register: data

  - name:  hypercore ping
    scale_computing.hypercore.api:
      cluster_instance:
        host: "https://{{ inventory_hostname }}"
        username: "{{scale_user}}"
        password: "{{scale_pass}}"
      action: get
      endpoint: /rest/v1/ping
    check_mode: no        

  - name:  list iso
    scale_computing.hypercore.iso_info:
      cluster_instance:
        host: "https://{{ inventory_hostname }}"
        username: "{{scale_user}}"
        password: "{{scale_pass}}"
    register: iso_list

  - name: show isos
    debug:
      var: iso_list

