---
- name: Initiate and monitor scupdate and restart VMs on SNS
  hosts: edge # use ansible-playbook -l group to limit application to specific groups
  connection: ansible.builtin.local
  gather_facts: False
  ignore_errors: yes # chesks will log failure if out of compliance
  #strategy: host_pinned #free  #allows each cluster to start next task before all clusters have finished current task
  environment:
    SC_HOST: "https://{{inventory_hostname}}"
    SC_USERNAME: "{{scale_user}}"
    SC_PASSWORD: "{{scale_pass}}"   
  
  roles:
  - hypercore_version