---
- name: Check clusters for important_vms list from cluster_inventory that should be running - and start in listed (priority) order 
  hosts: edge # use ansible-playbook -l group to limit application to specific groups - has tab completion for -l !
  connection: ansible.builtin.local
  gather_facts: false
  strategy: host_pinned # free  #allows each cluster to start next task before all clusters have finished current task

  tasks:
    - name: Start important_vms defined in cluster_inventory
      scale_computing.hypercore.vm_params:
        power_state: start
        vm_name: "{{ item }}"
      loop:  
        "{{ important_vms | from_yaml }}"
      when: important_vms is defined  # skip if no important_vms set for this cluster in inventory 
# could I also use vm tag in hypercore here?  or if tag = important?
