---
- name: Manage remote_support tunnel status across HyperCore fleet
  hosts: edge # use ansible-playbook -l group to limit application to specific groups
  connection: ansible.builtin.local
  gather_facts: False
  ignore_errors: yes # chesks will log failure if out of compliance
  #strategy: host_pinned #free  #allows each cluster to start next task before all clusters have finished current task

  
  roles:
  - remote_support