- name: Delete all AlertSyslogTargets across all inventory
  hosts: edge
  connection: local
  gather_facts: False
  environment:  #if set here - hypercore modules will automatically use this for each remote cluster - avoiding need to specify cluster_instance for each test
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}"
    SC_PASSWORD: "{{ scale_pass }}"
     
  tasks:
  - name: get current AlertSyslogTarget
    scale_computing.hypercore.api:
      action: get
      cluster_instance:
        host: "https://{{ inventory_hostname }}"
        username: "{{scale_user}}"
        password: "{{scale_pass}}"
      endpoint: /rest/v1/AlertSyslogTarget
    register: syslog

  - name: delete all AlertSyslogTargets
    scale_computing.hypercore.api:
      action: delete
      cluster_instance:
        host: "https://{{ inventory_hostname }}"
        username: "{{scale_user}}"
        password: "{{scale_pass}}"
      endpoint: /rest/v1/AlertSyslogTarget/{{ item.uuid }}
    loop: '{{ syslog.record | from_yaml_all | list }}'


