---
- name: Update a HyperCore single-node system
  hosts: all
  connection: local
  gather_facts: false
  # Comment out check_mode=true if you really want to start update.
#  check_mode: true
  environment:  #if set here - hypercore modules will automatically use this for each remote cluster - avoiding need to specify cluster_instance for each test
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}"
    SC_PASSWORD: "{{ scale_pass }}"
    SC_TIMEOUT: 600

  vars:
    desired_version: "{{ hypercore_desired_version }}"

  tasks:
    - name: Update HyperCore single-node system to a desired version
      include_role:
        name: scale_computing.hypercore.version_update_single_node
      vars:
        scale_computing_hypercore_desired_version: "{{ desired_version }}"