---
- name: change disk to virtio scsi  
  hosts: all
  vars:
    - vmname: "uefi-shell-test"
  connection: local
  gather_facts: false
  strategy: host_pinned # free  #allows each cluster to start next task before all clusters have finished current task
  environment:  # if set here - hypercore modules will automatically use this for each remote cluster - avoiding need to specify cluster_instance for each test
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user | default('admin') }}"
    SC_PASSWORD: "{{ scale_pass | default('admin') }}"
    SC_TIMEOUT: 15
  roles:

  pre_tasks:

  tasks:
    - name: Disk desired configuration for "{{ vmname }}
      scale_computing.hypercore.vm_disk:
        vm_name: "{{ vmname }}"
        items:
          - disk_slot: 1
            type: virtio_disk
            type_new: scsi_disk
            size: "{{60 * 1000 * 1000 * 1000 }}"
        state: present
