hc_alt_host: "ozt18a-02.lab.local"
pos_address:  10.6.42.22
pharm_address:  10.6.42.23
site_name: store3
hypercore_desired_version: 9.2.3.208915  #dell eol max version
hypercore_cluster_name: "ozt18a-lab-dd" 