edge:  # See all group vars section at bottom
  children: # todo - explore if this children level is actually required 
    region1:  # production site clusters in region 1 - indy region
      children:
        staging: # clusters here for pre-production staging / testing
          hosts:
            "szt15b-01.lab.local":
              hypercore_desired_version: 9.2.22.212325
              site_name: staging2
              hypercore_cluster_name: "staging-lab-dd"
              hc_alt_host: "szt15b-02.lab.local"
              SC_AUTH_METHOD: oidc

        corporate: # corporate owned stores
          hosts:
            "vlb04a-01.lab.local": # store2
              hypercore_desired_version: 9.3.0.212125
              site_name: store2
              hypercore_cluster_name: "vlb04a-lab-dd"
              hc_alt_host: "vlb04a-01.lab.local"
              pos_address: 10.6.42.21

            "vjb93a-02.lab.local":
              hypercore_desired_version: 9.3.0.212125
              hc_alt_host: "vjb93a-01.lab.local"
              pos_address: 10.6.42.21
              site_name: store5
              hypercore_cluster_name: "vjb93a-lab-dd"

          vars: # corporate vars
            SC_AUTH_METHOD: oidc

        franchise: # franchise owned stores managed as a service
          hosts:
            "vfz31a-01.lab.local": # store F1
#              hypercore_desired_version: 9.2.21.212248
              pos_address: 10.0.0.1
              site_name: storef1
              hypercore_cluster_name: "indyk8s-lab-dd"

            "veb120a-01.lab.local": # store F2
              pos_address: 10.0.0.2
              site_name: storef2
              hypercore_cluster_name: "indyvms-lab-dd"

          vars: # franchise vars
            hypercore_desired_version: 9.2.22.212325
            SC_AUTH_METHOD: local

      vars:  # region 1 group vars
        vm_image_url: 'smb://pm-edge;administrator:Scale2020!@192.168.1.248/azure-sync/ubuntu18_04-cloud-init'
        syslog_ip: '192.168.1.4'
        smbserver: 192.168.1.248
        smbpath: /azure-sync/ubuntu20_04-cloud-init
        winsmbpath: /azure-sync/win10IoT-uefi-cloudbase
        smbusername: pm-edge;administrator
        smbpassword: Scale2020!
        httpserver: 10.100.15.187
        timeSource: 192.168.1.42
        pharm_ram: "{{ '4 GB' | human_to_bytes }}"

    region2: # production site clusters in region 2 - westfield region
      hosts:
        "192.168.1.240.nip.io": # store101i
          hypercore_desired_version: 9.2.22.212325
          site_name: store101
          hypercore_cluster_name: "westfield-3271-dd"
          hc_alt_host: "192.168.1.241"
          pos_address: 192.168.1.200
          important_vms: |  # important vms that should be running also controls start order via playbook
            - github-runner
            - github-runner2
            - IEAM-westfield
            - acronisAgent
            - adfs-sso
          support_tunnel: 3271 # or false

        "192.168.1.230":
          hypercore_desired_version: 9.3.0.212125
          hypercore_cluster_name: "nuc11-dd-westfield"
          site_name: store1111
          support_tunnel: 3276  # or false

        "192.168.1.246.nip.io":  # store10
          hypercore_desired_version: 9.2.22.212325
          hypercore_cluster_name: "charlotte-3272-dd"
          pos_address: 192.168.1.201
          site_name: store102
          important_vms: |
            - acronisAppliance
          support_tunnel: 3272
          pharm_ram: "{{ '2 GB' | human_to_bytes }}"
          # hypercore_desired_version: 9.2.17.211525

        "192.168.1.242.nip.io":  # store104
          hypercore_desired_version: 9.2.22.212325 #9.1.24.211326 # experimental gpu passthrough
          hypercore_cluster_name: "newyork-3270-dd"
          site_name: store104
          pos_address: 192.168.1.203
          pharm_address: 192.168.1.204
          important_vms: |
            - pm-edge-svr
            - pm-edge-mgmt
            - acronisAppliance
            - rh85-ansible
            - aws-storage-gateway
          support_tunnel: 3270

      vars:  # region 2 group vars
        vm_image_url: 'smb://pm-edge;administrator:Scale2020!@192.168.1.248/azure-sync/ubuntu18_04-cloud-init'
        syslog_ip: '192.168.1.4'
        smbserver: 192.168.1.248
        smbpath: /azure-sync/ubuntu20_04-cloud-init
        winsmbpath: /azure-sync/win10IoT-uefi-cloudbase
        smbusername: pm-edge;administrator
        smbpassword: Scale2020!
        httpserver: 10.100.15.187
        timeSource: 192.168.1.42
        pharm_ram: "{{ '4 GB' | human_to_bytes }}"

    gcu: # production site clusters in region 3 - gce
      hosts:
        "10.6.43.98":  # gce
          hc_alt_host: "ia01b-02.lab.local"
          site_name: gcu-dr
          pos_address: 10.6.42.22
          hypercore_desired_version: 9.2.12.210899
          hypercore_cluster_name: "gcu-dr-dd"

  vars: # all group vars
    hypercore_desired_version: 9.2.22.212325 # view as desired minimum version for fleet
    scale_user: ansible
    scale_pass: ComplexPassword1234ans # be default ansible masks out what it think is passwords - so using simple password can conflict with VM names - etc.
    scale_admin_user: admin
    scale_admin_pass: admin
    support_tunnel: false
    dns_servers: 8.8.8.8
    timeZone: US/Eastern
    timeSource: time.google.com
    smtpServer: "smtp-relay.gmail.com"
    smtpport: 25
    smtpuseSSL: false
    smtpuseAuth: false
    smtpauthUser: ""
    smtpauthPassword: ""
    smtpfromAddress: "ddemlow@scalecomputing.com"

    client_id: d2298ec0-0596-49d2-9554-840a2fe20603
    shared_secret: ~0lI5n-_8dNbWmrrqqTE1v1iBcfO4__jfx
    config_url: https://login.microsoftonline.com/76d4c62a-a9ca-4dc2-9187-e2cc4d9abe7f/v2.0/.well-known/openid-configuration
    scopes: openid+profile
    company_name: Scale Computing
    contact: Dave Demlow
    phone: 3173850200
    regemail: dave@scalecomputing.com

    pharm_ram: "{{ '2 GB' | human_to_bytes }}"
    pos_ram: "{{ '4 GB' | human_to_bytes }}"

    http_import_uri: https://github.com/ddemlow/RestAPIExamples/raw/master/
    http_import_name: ubuntu20_04-cloud-init
    smbpath: /azure-sync/ubuntu20_04-cloud-init
    winsmbpath: /azure-sync/win10IoT-uefi-cloudbase
    smbusername: remotedc;administrator
    smbpassword: Scale2010
    httpserver: 10.100.15.187
    smbserver: 10.6.42.2

    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
