all:
  children:
    edge:
      children:
        staging: #clusters here for pre-production staging / testing
          hosts:
            "szt15b-01.lab.local": 
            "dzt09a-01.lab.local":
        region1:  #production site clusters in region 1 
          children:
            corporate: #corporate owned stores
              hosts:
                "ozt60b-01.lab.local": #store2
                "ozt18a-01.lab.local": #store3 
#                "10.100.24.28": #ztp demo        
            franchise: #franchise owned stores managed as a service
              hosts:
                "vfz31a-01.lab.local": #store F1
                "veb120a-01.lab.local": #store F2
                "szt15b-01.lab.local": #central IT staging
        region2: #production site clusters in region 2
          hosts:
            "192.168.1.240":  #store101
            "192.168.1.246":  #store102
            "192.168.1.245":  #store103
            "192.168.1.242":  #store104
