---
# tasks file for create users
  - name: Create ansible user account
    scale_computing.hypercore.user:
      cluster_instance:
        host: "https://{{ inventory_hostname }}"
        username: "{{ scale_admin_user }}"
        password: "{{ scale_admin_pass }}"
      state: present
      username: ansible
      password: ansible
      full_name: ansible
      session_limit: 0
      roles:
        - Admin
    async: 60
    poll: 0
    changed_when: false #password specified always results in change - this blocks that
  
 