---
# TODO iterate across all nodes in cluster?  - account for multiple tunnels in cluster?

  - name: Get remote support connection state
    scale_computing.hypercore.support_tunnel_info:
    register: rs_status

  # - name: Show remote_support out of compliance
  #   debug:
  #     msg: "{{inventory_hostname}} remote support status {{ (rs_status.record | from_json) ['tunnelOpen'] }} does not match policy {{ support_tunnel }}"
  #   when: ( rs_status.record.open ) != support_tunnel
  #   register: rs_change_needed

  # - name: rs in compliance - end host execution for host
  #   ansible.builtin.meta: end_host
  #   when: ( rs_status.record.open ) == support_tunnel

  - name: Close open tunnels that violate "false" policy
    scale_computing.hypercore.support_tunnel:
      state: absent
    register: rs_absent
    when: support_tunnel == false

  - name: Open remote support connection
    scale_computing.hypercore.support_tunnel:
      code: "{{ support_tunnel }}"
      state: present
    register: rs_present
    when: support_tunnel != false and ( rs_status.record.open ) != support_tunnel