---
# tasks file for hypercore_config role

- name: Create ansible user account
  scale_computing.hypercore.user:
    cluster_instance:
      host: "https://{{ inventory_hostname }}"
      username: "{{ scale_admin_user }}"
      password: "{{ scale_admin_pass }}"
    state: present
    username: "{{ scale_user }}"
    password: "{{ scale_pass }}"
    full_name: ansible (complex - cluster config role)
    session_limit: 0
    roles:
      - Admin
  async: 60
  poll: 0
  changed_when: false #password specified always results in change - this blocks that

- name: set HyperCore Cluster name to "{{ hypercore_cluster_name }}" #fails HyperCore server version=9.1.18.209840 does not match required version ==9.1.21 || >=9.2.11
  scale_computing.hypercore.cluster_name:
    name_new: "{{ hypercore_cluster_name }}"
  ignore_errors: true
#  when: hypercore_cluster_name is true  # not sure how blank / undefined cluster name is handled with this commented out

- name: set DNS configuration on "{{ hypercore_cluster_name }}" 
  scale_computing.hypercore.dns_config:
    search_domains:
      - lab.local
    dns_servers: 
      - "{{ dns_servers }}"
    state: set

- name: set OIDC Azure AD configuration on on "{{ hypercore_cluster_name }}" 
  scale_computing.hypercore.oidc_config:
    client_id: "{{ client_id }}"
    shared_secret: "{{ shared_secret }}"
    config_url: "{{ config_url }}"
    scopes: "{{ scopes }}"
  changed_when: false #will always report change due to secret 
  ignore_errors: true

- name: set NTP server to  "{{ timeSource }}" on "{{ hypercore_cluster_name }}" 
  scale_computing.hypercore.time_server:
    source: "{{ timeSource }}"
  ignore_errors: true  #temp workaround for empty uuid on new cluster
  failed_when: false

- name: set time zone to "{{ timeZone }}" on "{{ hypercore_cluster_name }}" 
  scale_computing.hypercore.time_zone:
    zone: "{{ timeZone }}"
  ignore_errors: true
  failed_when: false

- name: set Syslog server to "{{  syslog_ip }}" on "{{ hypercore_cluster_name }}" 
  scale_computing.hypercore.syslog_server:
    host: "{{  syslog_ip }}"
    port: 514
    protocol: udp
    state: present  
  ignore_errors: true

- name: set SMTP configuration "{{ smtpServer }}" (authorization disabled) 
  scale_computing.hypercore.smtp:
    server: "{{ smtpServer }}"
    port: "{{ smtpport }}"
    use_ssl: "{{ smtpuseSSL }}"
    from_address: "{{ smtpfromAddress }}"
  ignore_errors: true

- name: set smtp  Email Alert Recipient on "{{ hypercore_cluster_name }}" 
  scale_computing.hypercore.email_alert:
    email: "{{ regemail }}"
    state: present

- name: set HyperCore registration 
  scale_computing.hypercore.registration:
    company_name: "{{ company_name }}"
    contact: "{{ contact }}"
    phone: "{{ phone }}"
    email: "{{ regemail }}"
    state: present
  ignore_errors: true

- name: Open support tunnel "{{ support_tunnel}}" on "{{ hypercore_cluster_name }}"  #TODO - do I need to close if false?
  scale_computing.hypercore.support_tunnel:
    state: present
    code: "{{ support_tunnel }}"
  when: support_tunnel is not false

- name: Close support tunnel "{{ support_tunnel}}" on "{{ hypercore_cluster_name }}"  #TODO - do I need to close if false?
  scale_computing.hypercore.support_tunnel:
    state: absent
    code: "{{ support_tunnel }}"
  when: support_tunnel is false
  